### ISSUE TITLE
Removing or moving internal documents to github

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#111]
As you know, we have internal documents. I think it's time to remove the documents.
It has not been used long time.

Some of the documents might be moved to this repository.
But I think mentioning https://pypi.org/project/rpmrh/ as a variant of this tool is good enough.

How do you think?

**Comment by hroncok** [comment]
I don't know about any documents.

**Comment by junaruga** [comment]
@hroncok I sent you the URL on email.

**Comment by hroncok** [comment]
I agree that mentioning https://pypi.org/project/rpmrh/ as a variant of this tool is good enough. Everything else is not useful.

**Comment by junaruga** [comment]
@hroncok all right. @khardix how about you?

**Comment by khardix** [comment]
I'm fine with that.
