### ISSUE TITLE
Add CLI option to select number of retries

### ISSUE THREAD

**Issue by khardix** [sclorg/rpm-list-builder#15]
Right now, the number of retries for failed build is hard-coded to 3. During the debugging of a recipe, disabling the retrying would be beneficial.

I would like to have the option to set the number of retries from the command line.

**Comment by junaruga** [comment]
I like it too.

**Comment by ncoghlan** [comment]
For sclo-python, I'd definitely like the ability to disable this behaviour - I'd prefer for an unreliable build to just fail outright, rather than for it to give the appearance of working even though some package builds aren't working first time every time.

**Comment by junaruga** [comment]
The option: default: 0 (disable retry) may be good, considering your opinion.
