### ISSUE TITLE
Builder to modify modified RPM spec file when using --resume

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#18]
## Situation

For example, a build failed at position 5.

```
$ rpmlb \
  --build custom \
  --custom-file tests/fixtures/custom/rhpkg_internal_copr.yml \
  --work-directory $HOME/tmp/rpmlb_work_dir \
  ../rhscl-rebuild-recipes/ror.yml \
  rh-ror50 2>&1 | tee rpmlb.log
```

When it is run from position with resume option.

```
$ rpmlb \
  --build custom \
  --custom-file tests/fixtures/custom/rhpkg_internal_copr.yml \
  --work-directory $HOME/tmp/rpmlb_work_dir \
  --resume 5 \
  ../rhscl-rebuild-recipes/ror.yml \
  rh-ror50 2>&1 | tee rpmlb.log
```

```
$ cd tmp/rpmlb_work_dir/005/rubygem-diff-lcs
```

Updating to add `%global _with_bootstrap 1` to the RPM spec file that has already been updated on last build.

```
$ git diff rubygem-diff-lcs.spec
+# Edited by rpmlb
+%global _with_bootstrap 1 <== update by 2nd build.
+# Edited by rpmlb
+%global _with_bootstrap 1 <== update by 1st build.
+
...
```

This situation does not become an error as it is technically valid.
It does not become surface .

## Possible Solution

`https://github.com/sclorg/rpm-list-builder/blob/master/rpmlb/builder/base.py prepare function

1. will read the RPM spec file data from `foo.spec.orig` file if it exists.
2. if the orig file does not exist, will read from `foo.spec` file to get the RPM spec file data.

We can not use `git reset --hard HEAD` or other git command to reset the file content internally in `rpmlb` program because we will consider non-git environment too.

**Comment by khardix** [comment]
I did a typo in [commit message that should closed this one](https://github.com/sclorg/rpm-list-builder/commit/32a4a46c2e63f016f931b2ad7d7987c8afd70157). Closing manually.
