### ISSUE TITLE
Starting code coverage test

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#25]
I think starting code coverage test is useful for good quality of the tests.
Is there good coverage tool for Python?

**Comment by junaruga** [comment]
Code Climate as a service with Github?
Code Climate is popular tool for RubyGem packages.
https://codeclimate.com/browser-extension/
https://docs.codeclimate.com/v1.0/docs/test-coverage-python

**Comment by junaruga** [comment]
I found this document.
https://docs.python.org/devguide/coverage.html

**Comment by hroncok** [comment]
https://pypi.python.org/pypi/pytest-cov

Also https://codecov.io/

**Comment by junaruga** [comment]
Thanks for the information.
I am interested in using both `pytest-cov` and Code Climate.
Let me implement at first for `pytest-cov`.

**Comment by junaruga** [comment]
Here is a Ruby project.
You can see "coverage 98%" logo image in this page.
https://github.com/guard/listen

Coveralls has often been seen at Ruby projects, though I do not know Python projects.
https://coveralls.io/github/guard/listen
There is a API for Python.
https://coveralls.zendesk.com/hc/en-us/articles/201342869-Python

I think if we can use candidate tools at once as a trial, it is not good, we can remove it again.

If there is not any other objection, I want to try to use `pytest-cov`, Code Climate, Coveralls.

**Comment by junaruga** [comment]
I want to stop using Code Climate and Coveralls. Right now only using `pytest-cov` is good enough.

**Comment by junaruga** [comment]
I would close this ticket as we started the coverage test by https://github.com/sclorg/rpm-list-builder/pull/27
