### ISSUE TITLE
[RFE] Modularize the SPEC file editing

### ISSUE THREAD

**Issue by khardix** [sclorg/rpm-list-builder#33]
## The problem

There are several ways we need to edit the SPEC file during the build. The current solution has [issue](https://github.com/sclorg/rpm-list-builder/issues/18)(s), and is not very flexible. Since a builder might want to add specific edits not needed otherwise (i.e. some macros need adjustment only when building in koji), the system needs to change.

## Proposed solution

Let's leverage the python's excellent iteration protocol and generators:

1.  Have one function (context manager) that prepares and finalizes the editation:
    -   Backs up the original file if necessary.
    -   Opens the original for reading and the destination file for writing.
2.  Make the editations into generators, which generate lines of the result file.

### Possible implementation overview

```python
@contextlib.contextmanager
def edit_spec_file(self, spec: pathlib.Path):
    """Safely edit a spec file.

    Keyword arguments:
        spec: The spec-file to edit.

    Yields:
        Open handles for input and output file.
    """

    # Back-up the file & other preparation

    # Both open files are safely closed afterwards
    with original.open(mode='r') as src, target.open(mode='w') as dst:
        yield src, dst


def add_macros(self, source: Iterator[str], macros: Mapping[str, str]):
    """Add macros to the source stream."""

    for macro, value in macros.items():
        yield '%global {macro} {value}'.format(macro=macro, value=value)

    yield from source


def edit_macros(self, source: Iterator[str], macros: Mapping[str, str]):
    """Edit macros already present in the file."""

    for line in source:
        if matches_macro_regex(line):
            yield edited_line
        else:
            yield line

def extra_edits(self, source: Iterator[str]):
    """Builder-specifif SPEC file edits. Override if needed."""

    yield from source  # pass for generators
```

Usage:

```python
with self.edit_spec_file(path_to_spec) as (src, dst):
    edited = iter(src)

    edited = self.add_macros(edited, macros_to_add)
    edited = self.edit_macros(edited, macros_to_edit)
    edited = self.extra_edits(edited)
    # add any other file processing if needed

    dst.write('\n'.join(edited))
```

*Note:* For details on how it works, see [David Beazley's tutorial on generators](http://www.dabeaz.com/generators/).

**Comment by junaruga** [comment]
It does not matter.

**Comment by khardix** [comment]
@junaruga I'm not sure what you meant by the response – do you mean that you do not care which way it would be implemented?
@hroncok Can I ask about your thoughts on the matter?

**Comment by junaruga** [comment]
@khardix Yes. I used as the meaning. But as far as I know, "I do not care" is not polite. I think that I should not use that phrase except casual talk.

> http://dictionary.cambridge.org/grammar/british-grammar/common-verbs/matter
It doesn’t matter which one you use or implement.
No matter which one you implement.

**Comment by hroncok** [comment]
I don't really like the need to use `edited = iter(src)` at the beginning.

**Comment by hroncok** [comment]
Otherwise i like the approach, feel free to implement this.

**Comment by khardix** [comment]
> I don't really like the need to use `edited = iter(src)` at the beginning.

Turns out it is not needed, the handle itself is already an iterator:

```python
>>> def passthrough(it):
...     yield from it
...
>>> with open('3abc.txt') as infile:
...     print(''.join(passthrough(infile)))
...
abc
abc
abc
```

**Comment by hroncok** [comment]
I wasn't sure :)
