### ISSUE TITLE
Adding Travis Build status badge to README

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#43]
I want to add Travis Build status badge image to `README.md` like below site.
Because Seeing Travis page easily looks good to maintain this package.

https://github.com/kennethreitz/pipenv
build passing

How do you think?

**Comment by khardix** [comment]
I'm definitely for it, since the badge is also quick link to the travis itself.

I recommend checking https://shields.io/, where you can find links to various badges.

**Comment by junaruga** [comment]
Thanks. The URL a great references.
I am good enough to use only Travis right now.

I am interested in Code Climate (main feature and coverage feature) badges personally
But I want to try to use those by my repository, because I do not know if it is good or not.
