### ISSUE TITLE
Use git tags as canonical source for version strings

### ISSUE THREAD

**Issue by khardix** [sclorg/rpm-list-builder#60]
This issue is related to sclorg#50, sclorg#56.

Using [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm), it is possible to use git tags for filling the `version` metadata field in `setup.py`. This frees us from having to manually keep the version string somewhere in the package itself and manually synchronize that with git tags.

Other benefits include auto-generated "development version" for each commit (!) from the last tag.

**Comment by hroncok** [comment]
How does the work if you create a sdist and upload it to PyPI?

**Comment by khardix** [comment]
It works correctly – the version is "baked" into the release.

I do not know the structure of the sdist enough to be sure, but the version is present in `PKG-INFO` file, which the setuptools_scm uses as a fallback when no git is present.

**Comment by hroncok** [comment]
Cool
