### ISSUE TITLE
Adding Koji build in Users Guide

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#76]
@khardix I think that we need it on the document.
Can you write it?
https://github.com/sclorg/rpm-list-builder/blob/master/docs/users_guide.md

**Comment by khardix** [comment]
@junaruga Agreed, once I manage to get it working correctly, I will add it to the document.

**Comment by junaruga** [comment]
@khardix All right. thanks.

**Comment by junaruga** [comment]
Fixed by https://github.com/sclorg/rpm-list-builder/pull/99 .
