### ISSUE TITLE
Bumping version 1.1.0

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#89]
After fixing current 4 PRs #74, #80, #82, #88, and updating documents, I think it's time for us to release version 1.1.0.

What we do:
- Add version tag. `git tag -a v1.1.0 -m "v1.1.0 release"`
- Register RPM List Builder to PyPI.

How do you think?

**Comment by hroncok** [comment]
Register it rather sooner than later, so nobody steals the name.

**Comment by junaruga** [comment]
@hroncok OK I will register it with package name `rpmlb` today.

**Comment by junaruga** [comment]
I tried to register to pypi.
It looks previously the operation was register project and upload file.
But now it has been changed. the operation to register a project has gone. necessary project is only uploading a dist file.

```
$ python3 setup.py register -r https://test.pypi.org/legacy/
...
Registering rpmlb to https://test.pypi.org/legacy/
Server response (410): Project pre-registration is no longer required or supported, so continue directly to uploading files.
```

Ref:
https://pypi.org
https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html

I tried to upload current source.
But uploading was failed because of invalid version number `1.0.1.dev81+gfa889ae`.

```
$ python3 setup.py sdist upload
...
Submitting dist/rpmlb-1.0.1.dev81+gfa889ae.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): version: Cannot use PEP 440 local versions.
error: Upload failed (400): version: Cannot use PEP 440 local versions.
```

So, shall we release current source to get the project name `rpmlb` soon as `v1.1.0`?

Below are commands to run to upload source file.
Do I have a permission to push a tag information to this repository?

```
$ git tag -a v1.1.0 -m "v1.1.0 release"
$ git push origin v1.1.0
$ python3 setup.py sdist upload
```

**Comment by hroncok** [comment]
Oh. Didn't know that. So what about doing a 1.1.0-dev1 as a test that everything works?

> Do I have a permission to push a tag information to this repository?

I guess you do, only master branch is somehow protected (for everybody).


BTW also look at [twine](https://pypi.python.org/pypi/twine).

**Comment by hroncok** [comment]
In order to reserve the name, I've created v1.1.0-dev81 tag and uploaded sdist and wheel. let me know your PyPI username, so I can add you to the package.

**Comment by hroncok** [comment]
The tag is not pushed, because it breaks setuptools_scm with:

```
AssertionError: own dev numbers are unsupported
```

**Comment by hroncok** [comment]
Created a [1.1.0 milestone](https://github.com/sclorg/rpm-list-builder/milestone/1) so we know when to release.

**Comment by junaruga** [comment]
This repository has not been active long time.
After minimal PRs, shall we upload `rpmlb` v1.1.0 to pypi?
Then I guess our project is gong to be done in the meantime.

**Comment by junaruga** [comment]
@hhorak or @khardix I guess that all the task for v1.1.0 is finished. Can you bump version and release `rpmlb` to PyPI?

**Comment by junaruga** [comment]
I did `git tag` by Jan's request.

```
$ git tag -n
v1.0.0          v1.0.0 release

$ git tag -a 'v1.1.0' -m 'v1.1.0 release'

$ git tag -n
v1.0.0          v1.0.0 release
v1.1.0          v1.1.0 release

$ git push origin v1.1.0
```

**Comment by khardix** [comment]
And we are live: https://pypi.python.org/pypi/rpmlb
Good work, @junaruga.

**Comment by junaruga** [comment]
@khardix thanks for the releasing!
Congrats, everyone. We did it.
