### ISSUE TITLE
Run rpmlb with Ruby on Rails recipe for Copr

### ISSUE THREAD

**Issue by junaruga** [sclorg/rpm-list-builder#9]
This issue page is to manage to run `rpmlb` with Ruby on Rails recipe file [1] for Copr.

- See a document [2] to run it.
- Report the result here.

[1] https://github.com/sclorg/rhscl-rebuild-recipes/blob/master/ror.yml
[2] https://github.com/sclorg/rpm-list-builder/wiki/Example-to-build-with-Copr-for-Ruby-on-Rails-recipe

**Comment by junaruga** [comment]
Note: use below recipe file instead of [1]. I fixed 1 issue for `rubygem-diff-lcs` (position: 005) in the recipe file.
https://github.com/junaruga/rhscl-rebuild-recipes/blob/hotfix/fix-ror.yml/ror.yml

I failed to build `rubygem-flexmock` (position: 009). Maybe need to fix the content around the `rubygem-flexmock` in the recipe file.

**Comment by khardix** [comment]
I'm still running to build failures with `rubygem-diff-lcs` in the file provided 
by @junaruga. See the log: [rpmlb.txt](https://github.com/sclorg/rpm-list-builder/files/973555/rpmlb.txt).

I'm investigating this further.

**Comment by junaruga** [comment]
@khardix 

> https://github.com/junaruga/rhscl-rebuild-recipes/blob/hotfix/fix-ror.yml/ror.yml

Have you tried with above recipe file?
The file includes the fix for `rubygem-diff-lcs`: https://github.com/junaruga/rhscl-rebuild-recipes/commit/90dd8da5e31296e28c44ac8efa7b8684631cea97 .

**Comment by junaruga** [comment]
@khardix how about the root.log, build.log on the Copr server?

**Comment by junaruga** [comment]
@khardix 

> https://github.com/junaruga/rhscl-rebuild-recipes/commit/90dd8da5e31296e28c44ac8efa7b8684631cea97

Ah sorry above was my mistake.

And I found latest commit after checking `rubygem-diff-lcs`.

```
$ git sh 67bbf9537433da5a1319452288ee0c2dd4867bc6 rubygem-diff-lcs.spec
-%{?_with_bootstrap:    %global need_bootstrap  1}
+%{!?_with_bootstrap: %global bootstrap 0}
...
```

This latest code is 
If _with_bootstrap exists, bootstrap is 0,
if _with_bootstrap not exists, bootstrap is empty (kind of 0).

In the case, we can not enable bootsrap.

**Comment by junaruga** [comment]
The latest commit is a hack for `rubygem-flexmock` to pass build.
https://github.com/junaruga/rpm-list-builder/commits/hotfix/fix-internal-copr-yaml

**Comment by khardix** [comment]
With the hack in place, both `rubygem-flexmock` builds pass – good work.

However, now the build fails on `rubygem-railties`. Excerpt from `build.log.gz`:
```
Finished in 23.208449s, 0.4309 runs/s, 1.5081 assertions/s.
  1) Failure:
ApplicationTests::TestTest#test_simple_failed_test [test/application/test_test.rb:59]:
Failed assertion, no message given.
10 runs, 35 assertions, 1 failures, 0 errors, 0 skips
```
[The failed build](https://copr-be.cloud.fedoraproject.org/results/jstanek/scl-ror5/epel-7-x86_64/00550406-rubygem-railties/) is available for inspection in my [COPR](https://copr.fedorainfracloud.org/coprs/jstanek/scl-ror5/).

**Comment by junaruga** [comment]
@khardix The reason is

PATCH2 (rubygem-railties-5.0.1-Use-new-minitest-assert-false-message.patch) in `rubygem-railties.spec` is used for only minitest >= 5.9.0.
But for CentOS 7 environment, the dependency SCL rh-ruby23 is using minitest 5.8.3.
RHSCL dependency is rh-ruby24 minitest 5.10.1. So, the build is success in RHSCL.

Can you check below latest commit?
https://github.com/junaruga/rpm-list-builder/commits/hotfix/fix-internal-copr-yaml
Maybe it works.

Thanks.

**Comment by khardix** [comment]
I'm happy to report that with the last fix, the build passed in my internal COPR 🎆 🎉 .

Right now, I'm building it again in [my public COPR](https://copr.fedorainfracloud.org/coprs/jstanek/scl-ror5/) and it should be available in few hours for inspection.

If the public build successfully passes, I will start working on PR with changes to both this repo and [rhscl-rebuild-recipes](https://copr.fedorainfracloud.org/coprs/jstanek/scl-ror5/).

**Comment by junaruga** [comment]
Good job!

**Comment by junaruga** [comment]
Jan, I hope you will prepare PR for modified 2 files, recipe file and custom for copr at first.
Pavel is preparing Rails 5.1 now.
I want valid yaml file for Rails 5.0.
Thanks.

**Comment by khardix** [comment]
Here you go: [recipe file PR](https://github.com/sclorg/rhscl-rebuild-recipes/pull/18), [custom file PR](https://github.com/sclorg/rpm-list-builder/pull/30).

I'm not sure if or how to mark the PRs to automatically close this issue after merging, so if this is desirable, fell free to edit them or point me to the appropriate help page.

**Comment by junaruga** [comment]
Maybe the automatic closing is this https://help.github.com/articles/closing-issues-via-commit-messages/ .

But in this case, we want to close this ticket after both 2 PR will be merged.
I do not know the way to fill the use case.

And also I want your report about total running time on Copr on this PR page.

**Comment by khardix** [comment]
After bit of fiddling with COPR API and timestamps, here are the measurements (public COPR):
-   Pure build time (without waiting): `3:33:20`
-   Total build time (from start of first build to end of the last build, including waiting in between): `4:33:00`

**Comment by junaruga** [comment]
@khardix ok thanks for the report. It's practical time.
Feel free to close thicket.
